# Common for all jobs
common: &common
  working_directory: ~/project
  docker:
    - image: circleci/node:9.10-stretch

version: 2
jobs:
  test:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
  deploy:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build and deploy to GitHub Pages
          command: npm run deploy

workflows:
  version: 2
  deployment:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - master
            # "Note: The test job must also have a filters tags section,
            # as it is a transient dependency of the deploy job."
            # https://circleci.com/docs/2.0/workflows/
            tags:
              only: /.*/
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          requires:
            - test
