# Common for all jobs
common: &common
  docker:
    - image: circleci/node:9.10-stretch
  working_directory: ~/project

version: 2
jobs:
  test:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
        name: Install dependencies
        command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
        name: Run tests
        command: npm test
  deploy:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
        name: Install dependencies
        command: npm ci
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
        name: Build and deploy to GitHub Pages
        command: npm run deploy

workflows:
  version: 2
  test:
    filters:
      branches:
        only: dev
    jobs:
      - test
  test_and_deploy:
    filters:
      branches:
        only: master
    jobs:
      - test
      - deploy
