# Common for all jobs
common: &common
  working_directory: ~/project
  docker:
    - image: circleci/node:9-stretch

version: 2
jobs:
  test:
    <<: *common
    steps:
      - checkout

      - run:
          name: Node Version
          command: node --version

      - restore_cache:
          name: Restore node_modules cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm i

      - save_cache:
          name: Save node_modules cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm test

  deploy:
    <<: *common
    steps:
      - checkout

      - run:
          name: Node Version
          command: node --version

      - restore_cache:
          name: Restore node_modules cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm i

      - save_cache:
          name: Save node_modules cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Build and deploy to GitHub Pages
          command: npm run deploy

workflows:
  version: 2
  deployment:
    jobs:
      - test:
          filters:
            branches:
              only: dev
      - deploy:
          # Filters are OR instead of AND as one may assume, so ignore all
          # branches and only act on version tags
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
